    # MAX_LICENSE_ATOMIC_CAPACITY
    update control {
        Tmp-String-0 := "%{md5:%{Packet-Src-IP-Address}|%{NAS-IP-Address}|%{User-Name}|%{Calling-Station-Id}|%{NAS-Port}|%{Packet-Authentication-Vector}}"
        Tmp-String-1 := "%{sql:SELECT fn_reserve_license_slot('%{control:Tmp-String-0}', '%{User-Name}', '%{NAS-IP-Address}', '%{Calling-Station-Id}', '%{NAS-Port}', '%{Packet-Src-IP-Address}')}"
    }
    if (&control:Tmp-String-1 != "1") {
        if (&control:Tmp-String-1 == "0") {
            update reply {
                Reply-Message := "Concurrent session capacity reached"
            }
        }
        else {
            update reply {
                Reply-Message := "License verification unavailable or license invalid"
            }
        }
        reject
    }
    if (User-Name != "healthcheck") {
        update reply {
            Class += "maxcap:%{control:Tmp-String-0}"
        }
    }
