ï»؟prefix = /usr
exec_prefix = /usr
sysconfdir = /etc
localstatedir = /var
sbindir = ${exec_prefix}/sbin
logdir = /var/log/freeradius
raddbdir = /etc/raddb
radacctdir = ${logdir}/radacct

name = radiusd
confdir = ${raddbdir}
modconfdir = ${confdir}/mods-config
certdir = ${confdir}/certs
cadir = ${confdir}/certs
run_dir = ${localstatedir}/run/${name}

db_dir = ${raddbdir}
libdir = /usr/lib/freeradius

correct_escapes = true
max_request_time = 30
cleanup_delay = 5
max_requests = 16384

log {
    destination = stdout
    colourise = yes
    file = ${logdir}/radius.log
    syslog_facility = daemon
    stripped_names = no
    auth = yes
    auth_badpass = yes
    auth_goodpass = no
    msg_denied = "You are already logged in - access denied"
}

checkrad = ${sbindir}/checkrad

security {
    user = freerad
    group = freerad
    allow_core_dumps = no
}

$INCLUDE proxy.conf
$INCLUDE clients.conf
$INCLUDE ${confdir}/mods-enabled/
$INCLUDE ${confdir}/sites-enabled/
