[global]
port = 1701
auth file = /etc/ppp/chap-secrets
access control = no
debug network = no
debug packet = no
debug tunnel = no
debug state = no

[lns default]
ip range = 192.168.44.100-192.168.44.250
local ip = 192.168.44.1
refuse pap = no
require chap = yes
refuse chap = no
require authentication = yes
name = maxradius_l2tp
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
